create database if not exists teste;
use teste;
SET SQL_SAFE_UPDATES = 0;


create table CadFun (
	CODFUN   integer not null primary key,
    NOME     varchar(40) not null,
    DEPTO    char( 2),
    FUNCAO   char(20),
    SALARIO  decimal(10, 2));
    
describe CadFun;
describe CadFun CODFUN;

INSERT INTO cadfun(CODFUN, NOME, DEPTO, FUNCAO, SALARIO) VALUES (12, 'CARLOS ALBERTO', '3', 'VENDEDOR', 1530.00);
INSERT INTO cadfun(CODFUN, NOME, DEPTO, SALARIO) VALUES (44, 'JACIBA DA SILVA', '3', 1500.00);
INSERT INTO cadfun VALUES (2, 'WILSON DE MACEDO', '3', 'PROGRAMADOR', 1050.00);
INSERT INTO cadfun VALUES (5, 'AUGUSTO SOUZA', '3', 'PROGRAMADOR', 1050.00);
INSERT INTO cadfun VALUES (7, 'APARECIDA SILVA', '3', 'SECRETARIA', 1200.50);
INSERT INTO cadfun VALUES (15, 'MARCOS HENRIQUE', '2', 'GERENTE', 1985.75);

select * from cadfun;
SELECT NOME, CODFUN FROM cadfun WHERE DEPTO = '3';

SELECT NOME, SALARIO FROM cadfun ORDER BY NOME;
SELECT NOME, SALARIO FROM cadfun ORDER BY NOME DESC;
SELECT NOME, SALARIO FROM cadfun ORDER BY NOME DESC;
SELECT DEPTO, NOME FROM cadfun ORDER BY DEPTO, NOME DESC;
SELECT NOME FROM cadfun WHERE DEPTO = '3' ORDER BY NOME;

SELECT * FROM cadfun WHERE CODFUN = 7;
UPDATE cadfun SET SALARIO = 2300.56 WHERE CODFUN = 7;
SELECT * FROM cadfun WHERE CODFUN = 7;
SELECT * FROM cadfun WHERE NOME = 'ANA BASTOS';
UPDATE cadfun SET DEPTO = '3' WHERE NOME = 'ANA BASTOS';
SELECT * FROM cadfun WHERE NOME = 'ANA BASTOS';

SELECT * FROM cadfun;
UPDATE cadfun SET SALARIO = SALARIO * 1.10;
SELECT * FROM cadfun;

SELECT DISTINCT DEPTO FROM cadfun;
DELETE FROM cadfun WHERE DEPTO = '2';
SELECT * FROM cadfun;
DELETE FROM cadfun WHERE NOME = 'MARCELO SOUZA';
SELECT * FROM cadfun;

SELECT * FROM cadfun;
ALTER TABLE cadfun ADD ADMISSAO DATE;
SELECT * FROM cadfun;
UPDATE cadfun SET ADMISSAO = '2006-01-15' WHERE CODFUN = 2;
UPDATE cadfun SET ADMISSAO = '1999-10-21' WHERE CODFUN = 3;
UPDATE cadfun SET ADMISSAO = '2004-10-21' WHERE CODFUN = 4;
UPDATE cadfun SET ADMISSAO = '2006-04-26' WHERE CODFUN = 5;
UPDATE cadfun SET ADMISSAO = '1980-05-10' WHERE CODFUN = 7;
UPDATE cadfun SET ADMISSAO = '1999-12-15' WHERE CODFUN = 9;
UPDATE cadfun SET ADMISSAO = '2000-12-21' WHERE CODFUN = 12;
UPDATE cadfun SET ADMISSAO = '2000-10-21' WHERE CODFUN = 25;
SELECT * FROM cadfun;

INSERT INTO cadfun VALUES (15, 'MARCOS HENRIQUE', '2', 'GERENTE', 2184.33, '2006-05-25');
INSERT INTO cadfun VALUES (20, 'AUDREY TOLEDO', '2', 'SUPERVISORA', 1700.00, '2006-07-05');
INSERT INTO cadfun VALUES (22, 'SANDRA MANZANO', '2','ANALISTA', 2000.00, '2006-07-01');
INSERT INTO cadfun VALUES (24, 'MARCIO CANUTO', '2', 'PROGRAMADOR', 1200.00, '2006-07-10');
SELECT * FROM cadfun;

SELECT NOME, SALARIOFROM cadfun;
SELECT NOME, SALARIO + 100 FROM cadfun;
SELECT NOME, SALARIO FROM cadfun;
SELECT NOME, SALARIO * 1.20 FROM cadfun;
SELECT NOME, SALARIO FROM cadfun;

SELECT * FROM cadfun WHERE DEPTO = '5';
SELECT * FROM cadfun WHERE FUNCAO = 'VENDEDOR';
SELECT * FROM cadfun WHERE SALARIO <= 1700;
SELECT * FROM cadfun WHERE SALARIO > 1700 + 50;

SELECT * FROM cadfun WHERE (DEPTO = '3') AND (FUNCAO = 'PROGRAMADOR');
SELECT * FROM cadfun WHERE (DEPTO = '3') OR (DEPTO = '5');
SELECT * FROM cadfun WHERE NOT (FUNCAO = 'VENDEDOR');
SELECT * FROM cadfun WHERE (DEPTO = '5') XOR (FUNCAO = 'PROGRAMADOR');

ALTER TABLE cadfun ADD FILHOS SMALLINT;
SELECT NOME, FILHOS FROM cadfun;
SELECT CODFUN, NOME, FILHOS FROM cadfun WHERE FILHOS IS NULL;
SELECT CODFUN, NOME, FILHOS FROM cadfun WHERE NOT FILHOS IS NULL;
SELECT CODFUN, NOME, FILHOS FROM cadfun WHERE FILHOS IS NOT NULL;
SELECT CODFUN, NOME, FILHOS FROM cadfun WHERE NOT (FILHOS IS NULL);

UPDATE cadfun SET FILHOS = 1 WHERE CODFUN = 2;
UPDATE cadfun SET FILHOS = 3 WHERE CODFUN = 3;
UPDATE cadfun SET FILHOS = 2 WHERE CODFUN = 5;
UPDATE cadfun SET FILHOS = 1 WHERE CODFUN = 9;
UPDATE cadfun SET FILHOS = 4 WHERE CODFUN = 20;
UPDATE cadfun SET FILHOS = 3 WHERE CODFUN = 25;
SELECT CODFUN, NOME, FILHOS FROM cadfun;
SELECT CODFUN, NOME, FILHOS FROM cadfun WHERE FILHOS IS NULL;
SELECT CODFUN, NOME, FILHOS FROM cadfun WHERE NOT (FILHOS IS NULL);
SELECT * FROM cadfun WHERE SALARIO BETWEEN 1700 AND 2000;
SELECT * FROM cadfun WHERE SALARIO NOT BETWEEN 1700 AND 2000;
SELECT * FROM cadfun WHERE DEPTO IN ('2', '3');
SELECT * FROM cadfun WHERE DEPTO NOT IN ('2', '3');

SELECT * FROM cadfun WHERE NOME LIKE 'A%';
SELECT * FROM cadfun WHERE NOME LIKE '_A%';
SELECT * FROM cadfun WHERE NOME LIKE '%AN%';
SELECT * FROM cadfun WHERE SALARIO LIKE '%6';
SELECT * FROM cadfun WHERE SALARIO LIKE '_5%2';
SELECT * FROM cadfun WHERE NOME NOT LIKE '%AN%';

SELECT NOME, SALARIO FROM cadfun WHERE SALARIO LIKE '12%'; 